### ISSUE TITLE
Missing argument for InstagramAPI object instance

### ISSUE THREAD

**Issue by felipsmartins** [Instagram/python-instagram#148]
i've read the project docs and examples but when creating a instance of InstagramAPI and calling method a error occur:

```python
from instagram.client import InstagramAPI 

access_token = "YOUR_ACCESS_TOKEN" 
api = InstagramAPI(access_token=access_token) 
```

I'm wondering if it's a doc inconsistence because the above snippet should be:
```python
from instagram.client import InstagramAPI 

access_token = "YOUR_ACCESS_TOKEN" 
client_secret = "YOUR_CLIENT_SECRET"
api = InstagramAPI(client_secret=client_secret, access_token=access_token) 
```
If so, can I make a pull request?

Thanks!

**Comment by mrosati84** [comment]
I think this issue is actually part of #146 as it regards the same topic. I think it's necessary to

1. update the readme, as @felipsmartins says
2. check the `access_token` parameter and update the exception, because at the moment it's quite unclear:

```
Traceback (most recent call last):
  File "insta.py", line 5, in <module>
    recent_media, next_ = api.user_recent_media(user_id="userid", count=10)
  File "/home/matteo/.virtualenvs/instag/local/lib/python2.7/site-packages/instagram/bind.py", line 196, in _call
    return method.execute()
  File "/home/matteo/.virtualenvs/instag/local/lib/python2.7/site-packages/instagram/bind.py", line 182, in execute
    include_secret=self.include_secret)
  File "/home/matteo/.virtualenvs/instag/local/lib/python2.7/site-packages/instagram/oauth2.py", line 224, in prepare_request
    url = self._full_url_with_params(path, params, include_secret)
  File "/home/matteo/.virtualenvs/instag/local/lib/python2.7/site-packages/instagram/oauth2.py", line 148, in _full_url_with_params
    self._full_query_with_params(params) +
  File "/home/matteo/.virtualenvs/instag/local/lib/python2.7/site-packages/instagram/oauth2.py", line 144, in _full_url
    self._signed_request(path, {}, include_signed_request, include_secret))
  File "/home/matteo/.virtualenvs/instag/local/lib/python2.7/site-packages/instagram/oauth2.py", line 172, in _signed_request
    return "&sig=%s" % self._generate_sig(path, params, self.api.client_secret)
  File "/home/matteo/.virtualenvs/instag/local/lib/python2.7/site-packages/instagram/oauth2.py", line 127, in _generate_sig
    return  hmac.new(secret, sig, sha256).hexdigest()
  File "/usr/lib/python2.7/hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 71, in __init__
    if len(key) > blocksize:
TypeError: object of type 'NoneType' has no len()
```

**Comment by mdublin** [comment]
The ReadMe still hasn't been updated I don't think, ran into this same error message that mrosati84 has posted...

**Comment by felipsmartins** [comment]
True. It's important update docs.

**Comment by heatonjb** [comment]
The docs have been updated.
