### ISSUE TITLE
Error in HMAC() call

### ISSUE THREAD

**Issue by thiagoc** [Instagram/python-instagram#152]
```python
Traceback (most recent call last):
  File "app.py", line 153, in <module>
    index('ThomasGold') #52k
  File "app.py", line 18, in index
    users = api.user_search(name)
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/site-packages/instagram/bind.py
", line 196, in _call
    return method.execute()
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/site-packages/instagram/bind.py
", line 182, in execute
    include_secret=self.include_secret)
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/site-packages/instagram/oauth2.
py", line 224, in prepare_request
    url = self._full_url_with_params(path, params, include_secret)
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/site-packages/instagram/oauth2.
py", line 148, in _full_url_with_params
    self._full_query_with_params(params) +
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/site-packages/instagram/oauth2.
py", line 144, in _full_url
    self._signed_request(path, {}, include_signed_request, include_secret))
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/site-packages/instagram/oauth2.
py", line 172, in _signed_request
    return "&sig=%s" % self._generate_sig(path, params, self.api.client_secret)
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/site-packages/instagram/oauth2.
py", line 127, in _generate_sig
    return  hmac.new(secret, sig, sha256).hexdigest()
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/home/thiagoc/.virtualenvs/robo-instagram/lib/python3.4/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```

**Comment by orcaomar** [comment]
hi,

when will this get updated in the package on pypi? i'm fine using the github version, but right now deploying via pip installs the buggy version of oauth2.py.

thanks

omar

**Comment by jonathanmv** [comment]
I'd like to push for the pip version to be updated to include this fix. How can I help?

**Comment by ztane** [comment]
**SERIOUSLY NOW! WHY DIDN'T THIS BUG GET FIXED AND THE NEW VERSION RELEASED IN PYPI ALREADY?** 

Furthermore how in hell did this package land on PyPI with this broken Python 3 support anyway??? No one heard of TDD, CI, and such? Instagram built upon the Python infrastructure and the company is presently well-funded by Facebook, one would expect someone there care a bit contributing back, it cannot be that hard!

**Comment by ztane** [comment]
The change originates from https://github.com/Instagram/python-instagram/commit/79c41e1a8bb3a6a2269da12ed1cebedd3a420d31

**Comment by miohtama** [comment]
@ztane even if the company is having issues, you don't have to. I suggest you chill down and ask nicely. Meanwhile I can go to put some Python community misses you heart stickers at Instagram post box.

**Comment by miohtama** [comment]
Maybe if we ask real nicely Facebook even funds a new open source community manager. They are not exactly short of cash.

**Comment by miohtama** [comment]
Also maintaining your own fork is not that hard nowadays when pip can do direct git development installs.

**Comment by everilae** [comment]
Ppl have been asking nicely, and nothing happened.

**Comment by danisfermijohn** [comment]
Still getting the same issue. :(

**Comment by matt-g-adams** [comment]
Is there a workaround for this?

**Comment by danisfermijohn** [comment]
No, I am not aware of any workarounds. Guess we will have to wait for
Instagram to fix it.

On Wed, Jul 15, 2015 at 10:40 PM, Matthew Adams <notifications@github.com>
wrote:

> Is there a workaround for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Instagram/python-instagram/issues/152#issuecomment-121682065>
> .
>



-- 
Danis Fermi
Engineer, Virtusa

**Comment by jlnabais** [comment]
I'm experiencing the same issue.

**Comment by heatonjb** [comment]
1.3.2 has just been pushed to PyPi.  Please confirm the issue has been fixed.   
Sorry for the slow response on this.  
Please feel free to submit pull requests.

**Comment by jlnabais** [comment]
Still the same (python3.4).

used:

```
workon MyEnv
pip install --upgrade git+git://github.com/Instagram/python-instagram.git@dfeebe91cf389017e1786bd153d3d1285406ee9e
```

**Comment by jlnabais** [comment]
not quite the same (python3.4, python-instagram 1.3.2).

got (django StackTrace):

```
(404) Unable to parse response, not valid JSON.

(...)

response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
(...)views.py in get_instagram_media
                media = SocialFeed.get_instagram_media(user_id) ...
▶ Local vars
(...)social_networks.py in get_instagram_media
                    recent_media, next_ = cls.instagram_api.user_recent_media(user_id=user_id, count=count) ...
▶ Local vars
(...)/lib/python3.4/site-packages/instagram/bind.py in _call
                    return method.execute() ...
▶ Local vars
(...)/lib/python3.4/site-packages/instagram/bind.py in execute
                            content, next = self._do_api_request(url, method, body, headers) ...
▶ Local vars
(...)/lib/python3.4/site-packages/instagram/bind.py in _do_api_request
                            raise InstagramClientError('Unable to parse response, not valid JSON.', status_code=response['status']) 
```

My code (based on project documentation/stackoverflow)

```
class SocialFeed:
    instagram_api = InstagramAPI(client_id=settings.SOCIAL_AUTH_INSTAGRAM_KEY, client_secret=settings.SOCIAL_AUTH_INSTAGRAM_SECRET)

    (...)

    @classmethod
    def get_instagram_media(cls, user_id, count=6):
        recent_media, next_ = cls.instagram_api.user_recent_media(user_id=user_id, count=count)
        for media in recent_media:
            print(media.caption.text)
(...)
```

the user_id I'm testing with is "instagram"
