### ISSUE TITLE
Arguments on user_recent_media out of order in docs

### ISSUE THREAD

**Issue by andrewnguyen42** [Instagram/python-instagram#163]
The docs claim

`api.user_recent_media(user_id, count, max_id)`

but

`recent_photos = api.user_recent_media(user_id, count = photo_samples)`

will throw

Traceback (most recent call last):
  File "tag_data.py", line 27, in <module>
    recent_photos = api.user_recent_media(user_id, count = photo_samples)
  File "/Library/Python/2.7/site-packages/instagram/bind.py", line 195, in _call
    method = InstagramAPIMethod(api, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/instagram/bind.py", line 68, in __init__
    self._build_parameters(args, kwargs)
  File "/Library/Python/2.7/site-packages/instagram/bind.py", line 86, in _build_parameters
    raise InstagramClientError("Parameter %s already supplied" % key)
instagram.bind.InstagramClientError: Parameter count already supplied

**Comment by AlecsGherghel** [comment]
Try to pass the user_id as a named argument as well.

api.user_recent_media(user_id=user_id, count=photo_samples)

This way it will work.

It considers that user_id, the unnamed argument, is in fact the count value;  That's why it throws the Error.

**Comment by andrewnguyen42** [comment]
Sure, that will make it work. But the following

```recent_photos = api.user_recent_media(user_id, 10)[0]```
 ```print len(recent_photos)```

yields 0 and

```recent_photos = api.user_recent_media(user_id = user_id, count = 10)[0]```
 ```print len(recent_photos)```

yields 10

**Comment by AlecsGherghel** [comment]
Obviously, the second one works while in the first one it doesn't. I had some errors like that, when calling a method without sending the parameters explicit.

**Comment by rbpasker** [comment]
when you mix positional and keyword arguments, you have to make sure that the arguments you wish to pass as positional arguments correspond to the position in the `def` declaration.
