### ISSUE TITLE
user_recent_media breaks when "pagination" is null

### ISSUE THREAD

**Issue by dellsystem** [Instagram/python-instagram#176]
When I access the following endpoint:

```
https://api.instagram.com/v1/users/1795119/media/recent/?access_token=[access_token]
```

I get the following response:

```json
{
"pagination": null,
"meta": {
"code": 200
},
"data": []
}
```

I imagine this is a temporary error on the part of the Instagram API, as the user ([katespadeny](https://instagram.com/katespadeny/)) exists, has tweets, and is not private. That's fine, but if I use the python client to access the same endpoint, I get this error:

```python
>>> api.user_recent_media(user_id='1795119')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dellsystem/env/local/lib/python2.7/site-packages/instagram/bind.py", line 197, in _call
    return method.execute()
  File "/home/dellsystem/env/local/lib/python2.7/site-packages/instagram/bind.py", line 189, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "/home/dellsystem/env/local/lib/python2.7/site-packages/instagram/bind.py", line 161, in _do_api_request
    return api_responses, self._build_pagination_info(content_obj)
  File "/home/dellsystem/env/local/lib/python2.7/site-packages/instagram/bind.py", line 112, in _build_pagination_info
    return pagination.get('next_url')
AttributeError: 'NoneType' object has no attribute 'get'
```

whereas I would expect the python client to just return an empty list instead of raising an exception.

An easy workaround is to check that pagination is not None before attempting to access its "next_url" on line 112 of bind.py, but I don't know enough about how the Python client works internally to know if that's the right solution.

**Comment by suhaasprasad** [comment]
Did you figure out a work around for this? I'm running into the same issue.

**Comment by dellsystem** [comment]
@suhaasprasad Right now I just catch the AttributeError and treat the response as an empty list.
