### ISSUE TITLE
no module find

### ISSUE THREAD

**Issue by csselo** [Instagram/python-instagram#184]
Altought I achive to install it with pip, I coudnt start to work.

the error is
>>> from instagram.client import InstagramAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "instagram.py", line 1, in <module>
    from instagram.client import InstagramAPI
ImportError: No module named client

and files

/usr/lib/python3/dist-packages/friends/tests/data/instagram-login.dat
/usr/local/lib/python2.7/dist-packages/instagram
/usr/local/lib/python2.7/dist-packages/python_instagram-1.3.2.egg-info
/usr/local/lib/python2.7/dist-packages/instagram/__init__.py
/usr/local/lib/python2.7/dist-packages/instagram/__init__.pyc
/usr/local/lib/python2.7/dist-packages/instagram/bind.py
/usr/local/lib/python2.7/dist-packages/instagram/bind.pyc
/usr/local/lib/python2.7/dist-packages/instagram/client.py
/usr/local/lib/python2.7/dist-packages/instagram/client.pyc
/usr/local/lib/python2.7/dist-packages/instagram/helper.py
/usr/local/lib/python2.7/dist-packages/instagram/helper.pyc
/usr/local/lib/python2.7/dist-packages/instagram/json_import.py
/usr/local/lib/python2.7/dist-packages/instagram/json_import.pyc
/usr/local/lib/python2.7/dist-packages/instagram/models.py
/usr/local/lib/python2.7/dist-packages/instagram/models.pyc
/usr/local/lib/python2.7/dist-packages/instagram/oauth2.py
/usr/local/lib/python2.7/dist-packages/instagram/oauth2.pyc
/usr/local/lib/python2.7/dist-packages/instagram/subscriptions.py
/usr/local/lib/python2.7/dist-packages/instagram/subscriptions.pyc

**Comment by csselo** [comment]
solved

dont name your file "instagram.py"
