### ISSUE TITLE
request errors when using proxy

### ISSUE THREAD

**Issue by YangXS** [Instagram/python-instagram#200]
I search the recent medias of a specific user using the following code. ( I replaced my id and secret with '#').

I connect internet successfully using a proxy.
--------------------------------------------------------------------------------------------------
import os
import urllib2
from instagram.client import InstagramAPI

client_id = '#'
client_secret = '#'

api = InstagramAPI(client_id=client_id, client_secret=client_secret)
popular_media = api.media_popular(count=20)
for media in popular_media:
    print media.images['standard_resolution'].url
--------------------------------------------------------------------------------------------------

The errors are as follows.

Traceback (most recent call last):
  File "G:\workspace\instagram\search\main.py", line 27, in <module>
    popular_media = api.media_popular(count=20)
  File "build\bdist.win-amd64\egg\instagram\bind.py", line 197, in _call
    return method.execute()
  File "build\bdist.win-amd64\egg\instagram\bind.py", line 189, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "build\bdist.win-amd64\egg\instagram\bind.py", line 125, in _do_api_request
    response, content = OAuth2Request(self.api).make_request(url, method=method, body=body, headers=headers)
  File "build\bdist.win-amd64\egg\instagram\oauth2.py", line 238, in make_request
    return http_obj.request(url, method, body=body, headers=headers)
  File "C:\Program Files\Python2.7\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files\Python2.7\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files\Python2.7\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 1272, in _conn_request
    conn.connect()
  File "C:\Program Files\Python2.7\lib\site-packages\httplib2-0.9.2-py2.7.egg\httplib2\__init__.py", line 1075, in connect
    raise socket.error, msg
error: [Errno 10060]

**Comment by YangXS** [comment]
Finally resolved by adding proxy_info in the make_request function of oauth2.py

**Comment by alexandreesl** [comment]
can you please provide a snippet of how exacly did you solved this?

**Comment by YangXS** [comment]
I just revised the make_request function in the oauth2.py file as follows.

def make_request(self, url, method="GET", body=None, headers=None):
        headers = headers or {}
        if not 'User-Agent' in headers:
            headers.update({"User-Agent": "%s Python Client" % self.api.api_name})
        proxy_obj = httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, "127.0.0.1", 8580)
        http_obj = Http(proxy_info = proxy_obj) if six.PY3 else Http(disable_ssl_certificate_validation=True,proxy_info = proxy_obj)        
        return http_obj.request(url, method, body=body, headers=headers)
