### ISSUE TITLE
OAuthAccessTokenException-The access_token provided is invalid when using basic API

### ISSUE THREAD

**Issue by ninapavlich** [Instagram/python-instagram#206]
I have created a client using the Instagram API.

I am following the most basic example on your documentation:

    INSTAGRAM_CLIENT_ID='XXXXXXXXXX'
    INSTAGRAM_SECRET_CLIENT_ID='XXXXXXXXXX'
    from instagram.client import InstagramAPI
    api = InstagramAPI(client_id=INSTAGRAM_CLIENT_ID,   client_secret=INSTAGRAM_SECRET_CLIENT_ID)
    recent_media, next_ = api.user_recent_media(user_id="XXXXXXXXXX", count=10)

When I test this, I get the following error: 

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/username/Documents/Sites/project-name/venv/lib/python2.7/site-    packages/instagram/bind.py", line 197, in _call
        return method.execute()
      File "/Users/username/Documents/Sites/project-name/venv/lib/python2.7/site-packages/instagram/bind.py", line 189, in execute
        content, next = self._do_api_request(url, method, body, headers)
      File "/Users/username/Documents/Sites/project-name/venv/lib/python2.7/site-packages/instagram/bind.py", line 163, in _do_api_request
        raise InstagramAPIError(status_code, content_obj['meta']['error_type'], content_obj['meta']['error_message'])
    instagram.bind.InstagramAPIError: (400) OAuthAccessTokenException-The access_token provided is invalid.

I'm not quite sure why this is failing right out of the gate -- it's following the example exactly.

**Comment by shackra** [comment]
After overcoming #180 I'm experincing this as well. `python-instagram==1.3.2` running `Python 3.5.1`.

**Comment by shackra** [comment]
So, I figure it out. Here is a working code:

```
from instagram.client import InstagramAPI


# auth
client = InstagramAPI(client_id="AAAA",
                      client_secret="BBBB",
                      redirect_uri="http://localhost")
print(client.get_authorize_login_url(scope=["basic", "follower_list"]))
code = input().strip()
access_token = client.exchange_code_for_access_token(code)[0]
print("«{}»".format(access_token))

# we are authenticated, let's ask the followed users
client = InstagramAPI(client_secret="BBBB",
                      access_token=access_token)

users = []
followed, next_ = client.user_follows(user_id="self")
users.extend(followed)

while next_:
    followed_more, next_ = client.user_follows(user_id="self", with_next_url=next_)
    users.extend(followed_more)

print("Following {}".format(len(users)))
```

This was the output:

```
<Instagram url login>
«xxxx.yyyy.zzzzzzzzzzzzzzzz»
Following 0
```

I'm following more than 0 users, This may happen because [the users I'm following aren't sandbox users too](https://www.instagram.com/developer/sandbox/#api-behavior). Maybe this question at [Stackoverflow](http://stackoverflow.com/q/33886881/2020214) might tell us if this is normal or not.

## What was going wrong

The URL your user visits (generated by the line `print(client.get_authorize_login_url(scope=["basic", "follower_list"]))`) generates a code, not the actual access_token!

There is another pitfall with exchanging the code for the access token (as shown with `access_token = client.exchange_code_for_access_token(code)`), the API returns more data than the access code, it returns the your user's profile too, thus passing that garbage would make the petition fail with a HTTP 404 error code. The access code is on index 0, therefore the code `client.exchange_code_for_access_token(code)[0]` (note the `[0]`).

**Comment by asampat3090** [comment]
Despite having the correct access_token and requesting all scopes I can't access any the api endpoints. I keep getting the 404 error. Although i can verify that using your code I was able to get that I am following 0 people. Considering I am the only sandboxed user I am confused why I can't access any endpoints even after requesting all scopes.
