### ISSUE TITLE
Does Library work with new API Changes 

### ISSUE THREAD

**Issue by stanzheng** [Instagram/python-instagram#216]
Does this Library work with the new Sandbox Platform API updates?
http://developers.instagram.com/post/133424514006/instagram-platform-update

Using the readme example here, using app credentials created after the change raises;

```
Traceback (most recent call last):
  File "instagram.py", line 11, in <module>
    popular_media = api.media_popular(count=20)
  File "/usr/local/lib/python2.7/site-packages/instagram/bind.py", line 197, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/site-packages/instagram/bind.py", line 189, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "/usr/local/lib/python2.7/site-packages/instagram/bind.py", line 131, in _do_api_request
    raise InstagramClientError('Unable to parse response, not valid JSON.', status_code=response['status'])
``` 

whereas using older credentials I have for an older  project runs just fine. 
```
from instagram.client import InstagramAPI

access_token = "YOUR_ACCESS_TOKEN"
client_secret = "YOUR_CLIENT_SECRET"
api = InstagramAPI(access_token=access_token, client_secret=client_secret)
recent_media, next_ = api.user_recent_media(user_id="userid", count=10)
for media in recent_media:
   print media.caption.text
```

**Comment by stvkas** [comment]
I think you're right, @stanzheng. I'm having the same issue.

**Comment by skywritergr** [comment]
The library does work but the problem is that you are sandboxed. So the API is not returning a JSON object, rather than an error page (most likely html). To solve your problem you could try and catch your exception. 

Here is an example:
```
    try:
      photos = get_latest_photos(hashtag, number)
    except Exception as e:
      print("Oops! Something went wrong!")
      print(e)
      return jsonify(success=False) # I'm using flask
```

**Comment by anentropic** [comment]
this looks like a bug to me...

elsewhere the client aims to catch expected errors (rate limit etc) and raises an `InstagramAPIError` rather than this, which is more like an unexpected error

**Comment by skywritergr** [comment]
Basically yes. It should throw an InstagramAPIError.
