### ISSUE TITLE
 raise InstagramClientError('Unable to parse response, not valid JSON.', status_code=response['status']) instagram.bind.InstagramClientError: (400) Unable to parse response, not valid JSON.

### ISSUE THREAD

**Issue by datomnurdin** [Instagram/python-instagram#217]
I got this error message when trying trigger this line of code 

```
recent_media, next_ = api.user_recent_media(user_id="userid", count=10)
```

Error message
```
Traceback (most recent call last):
  File "python-instagram-stream.py", line 44, in <module>
    recent_media, next_ = api.user_recent_media(user_id="userid", count=10)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instagram/bind.py", line 197, in _call
    return method.execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instagram/bind.py", line 189, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instagram/bind.py", line 131, in _do_api_request
    raise InstagramClientError('Unable to parse response, not valid JSON.', status_code=response['status'])
instagram.bind.InstagramClientError: (400) Unable to parse response, not valid JSON.
```

Please advice. Thank you.

**Comment by BoldBigflank** [comment]
We had the same issue, it turns out we were passing in an invalid id.

**Comment by fgdeveloper** [comment]
I am passing what i know to be a valid ID (i've tried both the handle and the numeric). Any advice on how to pass that ID? I tried passing the string name, the numeric ID as a string (was told user not found) and then numeric ID as an integer.

**Comment by Logic-gate** [comment]
Try this #180

**Comment by fgdeveloper** [comment]
@Logic-gate Thank you. It was a sandbox mode issue - I cannot request any IDs outside of myself while in sandbox mode.
